version: "3"
services:
  app:
    restart: always
    build: .
    ports:
      - "80:4000"
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    environment:
      - NODE_ENV=production
# Uncomment the following to use a Mongo instance on the same server:
#     links:
#       - mongo
#   mongo:
#     image: mongo
#     restart: always
#     ports:
#       - "27017:27017"
#     volumes:
#       - data-volume:/data/db
# volumes:
#   data-volume: